-- Insert predefined muscle groups
INSERT INTO muscles (id, name, muscle_group) VALUES
    (uuid_generate_v4(), 'Pectoralis Major', 'CHEST'),
    (uuid_generate_v4(), 'Pectoralis Minor', 'CHEST'),
    (uuid_generate_v4(), 'Anterior Deltoid', 'DELTOIDS'),
    (uuid_generate_v4(), 'Lateral Deltoid', 'DELTOIDS'),
    (uuid_generate_v4(), 'Posterior Deltoid', 'DELTOIDS'),
    (uuid_generate_v4(), 'Trapezius', 'SHOULDERS'),
    (uuid_generate_v4(), 'Biceps Brachii', 'BICEPS'),
    (uuid_generate_v4(), 'Brachialis', 'BICEPS'),
    (uuid_generate_v4(), 'Triceps Brachii', 'TRICEPS'),
    (uuid_generate_v4(), 'Latissimus Dorsi', 'BACK'),
    (uuid_generate_v4(), 'Rhomboids', 'BACK'),
    (uuid_generate_v4(), 'Erector Spinae', 'BACK'),
    (uuid_generate_v4(), 'Forearm Flexors', 'FOREARMS'),
    (uuid_generate_v4(), 'Forearm Extensors', 'FOREARMS'),
    (uuid_generate_v4(), 'Gluteus Maximus', 'GLUTES'),
    (uuid_generate_v4(), 'Gluteus Medius', 'GLUTES'),
    (uuid_generate_v4(), 'Quadriceps', 'LEGS'),
    (uuid_generate_v4(), 'Hamstrings', 'LEGS'),
    (uuid_generate_v4(), 'Adductors', 'LEGS'),
    (uuid_generate_v4(), 'Abductors', 'LEGS'),
    (uuid_generate_v4(), 'Gastrocnemius', 'CALVES'),
    (uuid_generate_v4(), 'Soleus', 'CALVES');
